---
title: "Advanced Regression-Homework 1"
author: "Lin Le"
date: "2/23/2018"
output: html_document
---

## Section 1: initial setup

```{r}
# Load the dataset
democracy <- read.csv("democracy.csv", stringsAsFactors = FALSE, na.strings = ".")
```

## Section 2: initial data exploration
#### 2.1
```{r}
summary(democracy)
```

#### 2.2
```{r}
# remove NAs
sum(is.na(democracy$GDPW)) #there is no NA in GDPW
library(tidyr)
demo1 <- drop_na(democracy, POLLIB) # remove all rows where POLLIB vallues are NAs
```

```{r}
hist(demo1$POLLIB)
```

#### 2.3
```{r}
hist(demo1$GDPW, ylim = c(0,1000))
```

#### 2.4
```{r}
hist(log(demo1$GDPW), ylim = c(0,500))
# Conclusion: the distribution in the histogram using log transofmration appears to be less skewed than the previous one wihoiut using log transformation
```


## Section 3: explore relationships

#### 3.1-3.3
```{r}
library(ggplot2)

ggplot(demo1, aes(GDPW, POLLIB)) + geom_point()
ggplot(demo1, aes(GDPW, POLLIB)) + geom_jitter()

ggplot(demo1, aes(log(GDPW), POLLIB)) + geom_jitter()

# Conclusion: the distribution in the scatterplot using log transofmration appears to be less skewed than the previous one wihoiut using log transformation
```

#### 3.4
```{r}
# GDP of oil producing: 
  op <- democracy[democracy$OIL==1,]$GDPW
# GDP of non-oil producing: 
  nop <- democracy[democracy$OIL==0,]$GDPW
# boxplot
boxplot(op, nop, names=c("oil producing","non-oil producing"))
```

## Section 4: transform data and analyse

#### 4.1
```{r}
# mean GDP per capita in countries with at least 40 percent Catholics
mean(democracy[democracy$CATH >= 40,]$GDPW)
# mean GDP per capita for all countries
mean(democracy$GDPW)
# Conclusion: the mean GDP per capita in countries with at least 40 percent Catholics is higher than the mean GDP per capita of all countries.
```


#### 4.2
```{r}
# average GDP per capita in countries with...(ethnolinguistic fractionalization)
## remove NAs
demo2 <- drop_na(democracy,ELF60)

# greater than 60% 
mean(demo2[demo2$ELF60 > 0.6,]$GDPW)
# less than 60%
mean(demo2[demo2$ELF60 < 0.6,]$GDPW)
# missing 
mean(democracy[is.na(democracy$ELF60),]$GDPW)
```

#### 4.3
```{r}
## remove NAs in EDT
demo3 <- drop_na(democracy,EDT)
# median of the average years of education in 1985 for all countries
median(demo3[demo3$YEAR == 1985,]$EDT)
```

#### 4.4
```{r}
# The country closest to the median years of education in 1985 among all countries
library(dplyr)
# First, order rows BY EDT values from low to high
edu_sort <- arrange(demo3[demo3$YEAR == 1985,],EDT) 
str(edu_sort) # there are 113 objects
# since median is the one in the middle, i.e. the 57th in the series, then the closest to the median should be either the 56th or the 58th in this series.
edu_sort[56,]
edu_sort[57,]
edu_sort[58,]
# the 58th is closest country i.e. El Salvador (EDT = 5.725)
# then check whether there are other countries whose EDT value is the same as El Salvador's
edu_sort[edu_sort$EDT == 5.725,]
# it turns out that El Salvador is the only one
```

#### 4.5
```{r}
# The median of the average years of education in 1985 for democracies
median(demo3[demo3$REG == 1 & demo3$YEAR == 1985,]$EDT)
```

#### 4.6
```{r}
# The democracy closest to the median years of education in 1985 among all democracies
## repete the steps above: first, order from low to high
demo_sort <- arrange(demo3[demo3$REG == 1 & demo3$YEAR == 1985,],EDT)
str(demo_sort) # there are 45 objects
## pick out the 22nd and the 24th objects
demo_sort[22,]
demo_sort[23,] ## the median = 7.805
demo_sort[24,]
## the 24th is the closest one, i.e. France (EDT = 7.91)
## check whether France is the only one 
demo_sort[demo_sort$EDT == 7.91,]
## France is the only one
```

#### 4.7
```{r}
# The 25th and 75th percentiles of ethnolinguistic fractionalization for new and old countries
## check NAs in ethnolinguistic fractionalization and remove them
sum(is.na(democracy$ELF60))
demo4 <- drop_na(democracy,ELF60)
## then, selec the targeted countries by NEWC, and get the percentile value using "summary" function
### New countries
summary(demo4[demo4$NEWC == 1,]$ELF60)
# 25th percentile = 0.42
# 75th percentile = 0.75
### Old countries
summary(demo4[demo4$NEWC == 0,]$ELF60)
# 25th percentile =  0.06
# 75th percentile =  0.44
```

